In [1]:
import numpy as np
A = np.matrix([[2,1,3],
                [1,1,2],
                [3,2,5]])

#find eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(eigvecs)

[[-0.49079864 -0.65252078 -0.57735027]
 [-0.31970025  0.75130448 -0.57735027]
 [-0.81049889  0.0987837   0.57735027]]


In [7]:
B = np.diag(eigvals)
eigvecs@B@eigvecs.I

matrix([[2., 1., 3.],
        [1., 1., 2.],
        [3., 2., 5.]])

In [8]:
eigvecs.I

matrix([[-0.49079864, -0.31970025, -0.81049889],
        [-0.65252078,  0.75130448,  0.0987837 ],
        [-0.57735027, -0.57735027,  0.57735027]])